packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@types/node': ^25.6.0
  '@types/react': ^19.2.14
  '@vitest/coverage-v8': ^4.1.4
  '@vitest/ui': ^4.1.4
  tsdown: ^0.21.9
  typescript: ^6.0.0
  vitest: ^4.1.4
