export { runCodelore } from './runner.js';
export { analyzeParallelDev } from './analyzers/parallel-dev.js';
export type { FileStats } from './utils/git.js';
export type {
  CodeloreReport,
  RunCodeloreOptions,
  ChurnReport,
  FileChurn,
  ChurnCategory,
  BusFactorReport,
  FileBusFactor,
  BusFactorRisk,
  AgeMapReport,
  FileAge,
  AgeStatus,
  ContributorReport,
  Contributor,
  CursedFile,
  RepoMeta,
  ForensicsReport,
  FileForensics,
  ShamefulCommit,
  ParallelDevReport,
  FileParallelDev,
  ParallelWindow,
  LocReport,
  FileLocEntry,
  LanguageBreakdown,
  HotspotReport,
  HotspotEntry,
  HotspotCategory,
  CouplingReport,
  CoupledPair,
  FileCouplingProfile,
  ChurnVelocityReport,
  FileChurnVelocity,
  ChurnTrend,
  RewriteRatioReport,
  FileRewriteRatio,
  BlastRadiusReport,
  FileBlastRadius,
  DeadCodeReport,
  DeadCodeCandidate,
} from './types.js';
