export { runLore } from './runner.js';
export type {
  LoreReport as LoreReport,
  RunLoreOptions,
  ChurnReport,
  FileChurn,
  ChurnCategory,
  BusFactorReport,
  FileBusFactor,
  BusFactorRisk,
  AgeMapReport,
  FileAge,
  AgeStatus,
  ContributorReport,
  Contributor,
  CursedFile,
  RepoMeta,
  ForensicsReport,
  FileForensics,
  ShamefulCommit,
} from './types.js';
