export { runGitrelic } from './runner.js';
export { analyzeParallelDev } from './analyzers/parallel-dev.js';
export { analyzeHotspotClustering } from './analyzers/hotspot-clustering.js';
export type { CoAuthor, FileStats, RawCommit } from './utils/git.js';
export {
  classifyAuthor,
  isAiEmail,
  isBotEmail,
  aiProductName,
} from './utils/authorClassification.js';
export type { AuthorClass } from './utils/authorClassification.js';
export type {
  GitrelicReport,
  RunGitrelicOptions,
  ChurnReport,
  FileChurn,
  ChurnCategory,
  BusFactorReport,
  FileBusFactor,
  BusFactorRisk,
  AgeMapReport,
  FileAge,
  AgeStatus,
  ContributorReport,
  Contributor,
  CursedFile,
  RepoMeta,
  ForensicsReport,
  FileForensics,
  ShameByMonth,
  ShamefulCommit,
  ParallelDevReport,
  FileParallelDev,
  ParallelWindow,
  ParallelByMonth,
  LocReport,
  FileLocEntry,
  LanguageBreakdown,
  HotspotReport,
  HotspotEntry,
  HotspotCategory,
  CouplingReport,
  CoupledPair,
  FileCouplingProfile,
  ChurnVelocityReport,
  FileChurnVelocity,
  ChurnTrend,
  RewriteRatioReport,
  FileRewriteRatio,
  BlastRadiusReport,
  FileBlastRadius,
  DeadCodeReport,
  DeadCodeCandidate,
  TestCoverageProxyReport,
  DirectoryCoverage,
  GhostFilesReport,
  GhostFile,
  KnowledgeConcentrationReport,
  CoAuthorReport,
  CoAuthorPair,
  CoAuthorPairClassification,
  CoAuthorStats,
  AdoptionTier,
  AiAuthorStat,
  PerAuthorMixEntry,
  CoAuthorMonthEntry,
  HotspotClusterReport,
  HotspotCluster,
  ClusterMember,
  ClusterDimension,
  MultiSignalFile,
  ComplexityTrendReport,
  FileComplexityTrend,
  FileGrowthBucket,
  GrowthTrend,
  CommitTimingReport,
  FileTimingProfile,
  TimeOfDay,
  DayType,
  RenameTrackingReport,
  FileRenameChain,
  FileRename,
} from './types.js';
