import type { GitrelicReport } from '@gitrelic/core';

/**
 * Fills in default empty shapes for any analyzer field missing from a report.
 *
 * Reports generated by older CLI versions may predate newer analyzers — without
 * this normalization, any tab touching a missing field crashes with a TypeError
 * because the static `as GitrelicReport` cast provides no runtime safety.
 */
export function normalizeReport(raw: Partial<GitrelicReport>): GitrelicReport {
  return {
    timestamp: raw.timestamp ?? new Date().toISOString(),
    repoPath: raw.repoPath ?? '',
    repoName: raw.repoName ?? 'unknown',
    meta: {
      totalCommits: 0,
      totalFiles: 0,
      totalAuthors: 0,
      firstCommit: '',
      lastCommit: '',
      ageInDays: 0,
      primaryLanguage: 'unknown',
      branches: [],
      analyzedBranch: '',
      gitrelicVersion: '',
      ...raw.meta,
    },
    churn: raw.churn ?? {
      files: [],
      topFiles: [],
      hotspotCount: 0,
      summary: 'Not available',
    },
    busFactors: raw.busFactors ?? {
      files: [],
      criticalFiles: [],
      overallBusFactor: 0,
      summary: 'Not available',
    },
    ageMap: {
      files: raw.ageMap?.files ?? [],
      staleFiles: raw.ageMap?.staleFiles ?? [],
      ancientFiles: raw.ageMap?.ancientFiles ?? [],
      medianAgeDays: raw.ageMap?.medianAgeDays ?? 0,
      thresholds: raw.ageMap?.thresholds ?? {
        freshLimit: Math.round((raw.meta?.ageInDays ?? 0) * 0.08),
        agingLimit: Math.round((raw.meta?.ageInDays ?? 0) * 0.33),
        staleLimit: Math.round((raw.meta?.ageInDays ?? 0) * 0.66),
      },
      summary: raw.ageMap?.summary ?? 'Not available',
    },
    contributors: raw.contributors ?? {
      contributors: [],
      activeContributors: [],
      ghostContributors: [],
      topContributor: {
        email: '',
        name: '',
        commitCount: 0,
        firstCommit: '',
        lastCommit: '',
        filesOwned: 0,
        linesChanged: 0,
        activeDays: 0,
        focusAreas: [],
        isActive: false,
      },
      summary: 'Not available',
    },
    cursedFiles: raw.cursedFiles ?? [],
    forensics: raw.forensics ?? {
      files: [],
      shameLeaderboard: [],
      totalShameCommits: 0,
      keywordTiers: { critical: 0, moderate: 0, mild: 0 },
      byMonth: [],
      summary: 'Not available',
    },
    parallelDev: raw.parallelDev ?? {
      files: [],
      hotFiles: [],
      totalParallelFiles: 0,
      summary: 'Not available',
    },
    loc: raw.loc ?? {
      totalFiles: 0,
      totalLines: 0,
      files: [],
      languages: [],
      summary: 'Not available',
    },
    hotspots: raw.hotspots ?? {
      files: [],
      topHotspots: [],
      summary: 'Not available',
    },
    coupling: raw.coupling ?? {
      pairs: [],
      fileProfiles: [],
      topPairs: [],
      summary: 'Not available',
    },
    churnVelocity: raw.churnVelocity ?? {
      files: [],
      acceleratingFiles: [],
      summary: 'Not available',
    },
    rewriteRatio: raw.rewriteRatio ?? {
      files: [],
      topRewriters: [],
      totalInsertions: 0,
      totalDeletions: 0,
      highRewrite: 0,
      summary: 'Not available',
    },
    blastRadius: raw.blastRadius ?? {
      files: [],
      topBlasters: [],
      summary: 'Not available',
    },
    deadCode: raw.deadCode ?? {
      candidates: [],
      totalDeadFiles: 0,
      totalDeadLines: 0,
      summary: 'Not available',
    },
    testCoverage: {
      directories: raw.testCoverage?.directories ?? [],
      uncoveredDirectories: raw.testCoverage?.uncoveredDirectories ?? [],
      files: raw.testCoverage?.files ?? [],
      overallRatio: raw.testCoverage?.overallRatio ?? 0,
      summary: raw.testCoverage?.summary ?? 'Not available',
    },
    ghostFiles: raw.ghostFiles ?? {
      files: [],
      totalGhostFiles: 0,
      summary: 'Not available',
    },
    knowledgeConcentration: raw.knowledgeConcentration ?? {
      singleAuthorFiles: 0,
      totalFiles: 0,
      concentrationIndex: 0,
      summary: 'Not available',
    },
    coAuthors: raw.coAuthors ?? {
      pairs: [],
      authorStats: [],
      totalCoAuthoredCommits: 0,
      summary: 'Not available',
    },
    hotspotClusters: raw.hotspotClusters ?? {
      clusters: [],
      multiSignalFiles: [],
      summary: 'Not available',
    },
    complexityTrend: raw.complexityTrend ?? {
      files: [],
      growingFiles: [],
      shrinkingFiles: [],
      summary: 'Not available',
    },
    commitTiming: raw.commitTiming ?? {
      files: [],
      stressFiles: [],
      repoLateNightPercent: 0,
      repoWeekendPercent: 0,
      summary: 'Not available',
    },
    renameTracking: raw.renameTracking ?? {
      renames: [],
      chains: [],
      totalRenames: 0,
      filesWithRenames: 0,
      summary: 'Not available',
    },
    commits: raw.commits ?? [],
  };
}
