import type { GitrelicReport } from '@gitrelic/core';

/**
 * Fills in default empty shapes for any analyzer field missing from a report.
 *
 * Reports generated by older CLI versions may predate newer analyzers — without
 * this normalization, any tab touching a missing field crashes with a TypeError
 * because the static `as GitrelicReport` cast provides no runtime safety.
 */
export function normalizeReport(raw: Partial<GitrelicReport>): GitrelicReport {
  return {
    timestamp: raw.timestamp ?? new Date().toISOString(),
    repoPath: raw.repoPath ?? '',
    repoName: raw.repoName ?? 'unknown',
    meta: {
      totalCommits: 0,
      totalFiles: 0,
      totalAuthors: 0,
      firstCommit: '',
      lastCommit: '',
      ageInDays: 0,
      primaryLanguage: 'unknown',
      branches: [],
      analyzedBranch: '',
      gitrelicVersion: '',
      ...raw.meta,
    },
    churn: raw.churn ?? {
      files: [],
      topFiles: [],
      hotspotCount: 0,
      summary: 'Not available',
    },
    busFactors: raw.busFactors ?? {
      files: [],
      criticalFiles: [],
      overallBusFactor: 0,
      summary: 'Not available',
    },
    ageMap: {
      files: raw.ageMap?.files ?? [],
      staleFiles: raw.ageMap?.staleFiles ?? [],
      ancientFiles: raw.ageMap?.ancientFiles ?? [],
      medianAgeDays: raw.ageMap?.medianAgeDays ?? 0,
      // Mirrors `getAgeThresholds` in packages/core/src/analyzers/age-map.ts —
      // duplicated because apps/web only does `import type` from @gitrelic/core
      // (value imports leak Node into the browser bundle). Keep these multipliers
      // in sync with core if they change.
      thresholds: raw.ageMap?.thresholds ?? {
        freshLimit: Math.round((raw.meta?.ageInDays ?? 0) * 0.08),
        agingLimit: Math.round((raw.meta?.ageInDays ?? 0) * 0.33),
        staleLimit: Math.round((raw.meta?.ageInDays ?? 0) * 0.66),
      },
      summary: raw.ageMap?.summary ?? 'Not available',
    },
    contributors: {
      contributors: raw.contributors?.contributors ?? [],
      activeContributors: raw.contributors?.activeContributors ?? [],
      ghostContributors: raw.contributors?.ghostContributors ?? [],
      topContributor: raw.contributors?.topContributor ?? {
        email: '',
        name: '',
        commitCount: 0,
        firstCommit: '',
        lastCommit: '',
        filesOwned: 0,
        linesChanged: 0,
        activeDays: 0,
        focusAreas: [],
        isActive: false,
        isGhost: false,
      },
      summary: raw.contributors?.summary ?? 'Not available',
      top3CommitShare: raw.contributors?.top3CommitShare ?? 0,
      newcomers90d: raw.contributors?.newcomers90d ?? 0,
    },
    cursedFiles: raw.cursedFiles ?? [],
    forensics: raw.forensics ?? {
      files: [],
      shameLeaderboard: [],
      totalShameCommits: 0,
      keywordTiers: { critical: 0, moderate: 0, mild: 0 },
      byMonth: [],
      summary: 'Not available',
    },
    parallelDev: raw.parallelDev ?? {
      files: [],
      hotFiles: [],
      totalParallelFiles: 0,
      highParallel: 0,
      tierMix: { low: 0, medium: 0, high: 0, critical: 0 },
      byMonth: [],
      summary: 'Not available',
    },
    loc: raw.loc ?? {
      totalFiles: 0,
      totalLines: 0,
      files: [],
      languages: [],
      summary: 'Not available',
    },
    hotspots: raw.hotspots ?? {
      files: [],
      topHotspots: [],
      summary: 'Not available',
    },
    coupling: raw.coupling ?? {
      pairs: [],
      fileProfiles: [],
      topPairs: [],
      summary: 'Not available',
    },
    churnVelocity: raw.churnVelocity ?? {
      files: [],
      acceleratingFiles: [],
      summary: 'Not available',
    },
    rewriteRatio: raw.rewriteRatio ?? {
      files: [],
      topRewriters: [],
      totalInsertions: 0,
      totalDeletions: 0,
      highRewrite: 0,
      summary: 'Not available',
    },
    blastRadius: raw.blastRadius ?? {
      files: [],
      topBlasters: [],
      summary: 'Not available',
    },
    deadCode: raw.deadCode ?? {
      candidates: [],
      totalDeadFiles: 0,
      totalDeadLines: 0,
      summary: 'Not available',
    },
    testCoverage: {
      directories: raw.testCoverage?.directories ?? [],
      uncoveredDirectories: raw.testCoverage?.uncoveredDirectories ?? [],
      files: raw.testCoverage?.files ?? [],
      overallRatio: raw.testCoverage?.overallRatio ?? 0,
      summary: raw.testCoverage?.summary ?? 'Not available',
    },
    ghostFiles: {
      files: raw.ghostFiles?.files ?? [],
      totalGhostFiles: raw.ghostFiles?.totalGhostFiles ?? 0,
      ghostOwners: raw.ghostFiles?.ghostOwners ?? 0,
      ghostLoc: raw.ghostFiles?.ghostLoc ?? 0,
      tierMix: raw.ghostFiles?.tierMix ?? { trueGhost: 0, fading: 0 },
      summary: raw.ghostFiles?.summary ?? 'Not available',
    },
    knowledgeConcentration: raw.knowledgeConcentration ?? {
      singleAuthorFiles: 0,
      totalFiles: 0,
      concentrationIndex: 0,
      summary: 'Not available',
    },
    coAuthors: {
      pairs: raw.coAuthors?.pairs ?? [],
      authorStats: raw.coAuthors?.authorStats ?? [],
      totalCoAuthoredCommits: raw.coAuthors?.totalCoAuthoredCommits ?? 0,
      summary: raw.coAuthors?.summary ?? 'Not available',
      aiAssistedCommits: raw.coAuthors?.aiAssistedCommits ?? 0,
      humanAuthoredCommits: raw.coAuthors?.humanAuthoredCommits ?? 0,
      aiAdoptionPercent: raw.coAuthors?.aiAdoptionPercent ?? 0,
      aiAdoptionTier: raw.coAuthors?.aiAdoptionTier ?? 'none',
      aiAuthors: raw.coAuthors?.aiAuthors ?? [],
      humanPairs: raw.coAuthors?.humanPairs ?? [],
      filteredBotCommits: raw.coAuthors?.filteredBotCommits ?? 0,
      byMonth: raw.coAuthors?.byMonth ?? [],
      perAuthorMix: raw.coAuthors?.perAuthorMix ?? [],
    },
    hotspotClusters: raw.hotspotClusters ?? {
      clusters: [],
      multiSignalFiles: [],
      summary: 'Not available',
    },
    complexityTrend: raw.complexityTrend ?? {
      files: [],
      growingFiles: [],
      shrinkingFiles: [],
      summary: 'Not available',
    },
    commitTiming: {
      files: raw.commitTiming?.files ?? [],
      stressFiles: raw.commitTiming?.stressFiles ?? [],
      repoLateNightPercent: raw.commitTiming?.repoLateNightPercent ?? 0,
      repoWeekendPercent: raw.commitTiming?.repoWeekendPercent ?? 0,
      summary: raw.commitTiming?.summary ?? 'Not available',
      repoHourDayMatrix:
        raw.commitTiming?.repoHourDayMatrix ??
        Array.from({ length: 7 }, () => new Array<number>(24).fill(0)),
      highStress: raw.commitTiming?.highStress ?? 0,
      tierMix: raw.commitTiming?.tierMix ?? {
        low: 0,
        medium: 0,
        high: 0,
        critical: 0,
      },
      byMonth: raw.commitTiming?.byMonth ?? [],
      authorStress: raw.commitTiming?.authorStress ?? [],
    },
    renameTracking: raw.renameTracking ?? {
      renames: [],
      chains: [],
      totalRenames: 0,
      filesWithRenames: 0,
      summary: 'Not available',
    },
    commits: raw.commits ?? [],
  };
}
